import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const buyHtml = await readFile(new URL("../buy.html", import.meta.url), "utf8");
const payHtml = await readFile(new URL("../pay.html", import.meta.url), "utf8");
const afterPayHtml = await readFile(new URL("../after-pay.html", import.meta.url), "utf8");

assert.ok(buyHtml.includes("offerdesk.manual.order.id"));
assert.ok(buyHtml.includes("copyManualOrderButton"));
assert.ok(buyHtml.includes("manualOrderId"));
assert.ok(buyHtml.includes("manualBuyerForm"));
assert.ok(buyHtml.includes("manualBuyerEmail"));
assert.ok(buyHtml.includes("manualBuyerName"));
assert.ok(buyHtml.includes("offerdesk.manual.buyer.email"));
assert.ok(buyHtml.includes("offerdesk.manual.buyer.name"));
assert.ok(buyHtml.includes("getManualOrderId()"));
assert.ok(buyHtml.includes("updateManualClaimLink()"));
assert.ok(buyHtml.includes("requireManualBuyerEmail"));
assert.ok(buyHtml.includes('manualClaimButton.addEventListener("click", requireManualBuyerEmail)'));
assert.ok(buyHtml.includes("manualBuyerEmail.checkValidity()"));
assert.ok(buyHtml.includes("buyer_email"));
assert.ok(buyHtml.includes("payer_name"));
assert.ok(buyHtml.includes("function deliveryStatusText"));
assert.ok(buyHtml.includes('order.emailDeliveryStatus === "failed"'));
assert.ok(buyHtml.includes("授权邮件暂未发出，先复制页面上的授权码"));
assert.ok(buyHtml.includes('order.emailDeliveryStatus === "sent"'));
assert.ok(buyHtml.includes('<link rel="stylesheet" href="./site.css" />'));
assert.ok(buyHtml.includes('class="btn primary" id="checkoutButton"'));
assert.ok(buyHtml.includes('checkoutButton.classList.remove("primary")'));
assert.ok(!buyHtml.includes('class="btn green"'));
assert.ok(!buyHtml.includes("border-radius: 999px"));
assert.ok(!buyHtml.includes('font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial'));

assert.ok(afterPayHtml.includes("incomingOrderId"));
assert.ok(afterPayHtml.includes("incomingBuyerEmail"));
assert.ok(afterPayHtml.includes("incomingPayerName"));
assert.ok(afterPayHtml.includes("setStoredOrderId(incomingOrderId)"));
assert.ok(afterPayHtml.includes("setStoredManualBuyerEmail(incomingBuyerEmail)"));
assert.ok(afterPayHtml.includes("setStoredManualBuyerName(incomingPayerName)"));
assert.ok(afterPayHtml.includes("offerdesk.manual.order.id"));
assert.ok(afterPayHtml.includes("offerdesk.manual.buyer.email"));
assert.ok(afterPayHtml.includes("offerdesk.manual.buyer.name"));
assert.ok(afterPayHtml.includes("claim-grid"));
assert.ok(afterPayHtml.includes("orderForSubject"));
assert.ok(afterPayHtml.includes("OfferDesk 专业版授权码领取 ${orderForSubject}"));
assert.ok(afterPayHtml.includes('<link rel="stylesheet" href="./site.css" />'));
assert.ok(afterPayHtml.includes('class="btn primary" id="mailLink"'));
assert.ok(!afterPayHtml.includes("border-radius: 999px"));
assert.ok(!afterPayHtml.includes('font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial'));

assert.ok(payHtml.includes("旧付款入口"));
assert.ok(payHtml.includes("去成交页填写邮箱并付款"));
assert.ok(payHtml.includes('<link rel="stylesheet" href="./site.css" />'));
assert.ok(payHtml.includes('class="card old-pay-card"'));
assert.ok(payHtml.includes('class="btn primary" href="./buy.html"'));
assert.ok(!payHtml.includes("https://qr.alipay.com/"));
assert.ok(!payHtml.includes("border-radius: 999px"));
assert.ok(!payHtml.includes('font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial'));

console.log("manual checkout flow tests passed");
