import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const buyHtml = await readFile(new URL("../buy.html", import.meta.url), "utf8");
const payHtml = await readFile(new URL("../pay.html", import.meta.url), "utf8");
const afterPayHtml = await readFile(new URL("../after-pay.html", import.meta.url), "utf8");

assert.ok(buyHtml.includes("offerdesk.manual.order.id"));
assert.ok(buyHtml.includes("copyManualOrderButton"));
assert.ok(buyHtml.includes("copyPaymentRemarkButton"));
assert.ok(buyHtml.includes("manualOrderId"));
assert.ok(buyHtml.includes("manualPaymentRemark"));
assert.ok(buyHtml.includes("manualBuyerForm"));
assert.ok(buyHtml.includes("manualBuyerEmail"));
assert.ok(buyHtml.includes("manualBuyerName"));
assert.ok(buyHtml.includes("handoff-box"));
assert.ok(buyHtml.includes("付款前先确认这 3 件事"));
assert.ok(buyHtml.includes("付款备注建议填订单号"));
assert.ok(buyHtml.includes("付款备注已复制"));
assert.ok(buyHtml.includes("页面会自动带上订单号、邮箱和报价来源"));
assert.ok(buyHtml.includes("不会假装秒发"));
assert.ok(buyHtml.includes("offerdesk.manual.buyer.email"));
assert.ok(buyHtml.includes("offerdesk.manual.buyer.name"));
assert.ok(buyHtml.includes("getManualOrderId()"));
assert.ok(buyHtml.includes("updateManualClaimLink()"));
assert.ok(buyHtml.includes("requireManualBuyerEmail"));
assert.ok(buyHtml.includes('manualClaimButton.addEventListener("click", requireManualBuyerEmail)'));
assert.ok(buyHtml.includes("manualBuyerEmail.checkValidity()"));
assert.ok(buyHtml.includes("buyer_email"));
assert.ok(buyHtml.includes("payer_name"));
assert.ok(buyHtml.includes("addPaymentContextParams(params)"));
assert.ok(buyHtml.includes('params.set("project", context.project)'));
assert.ok(buyHtml.includes('params.set("quote_total", context.quoteTotal)'));
assert.ok(buyHtml.includes("function readPaymentContextFromUrl"));
assert.ok(buyHtml.includes("function deliveryStatusText"));
assert.ok(buyHtml.includes('order.emailDeliveryStatus === "failed"'));
assert.ok(buyHtml.includes("授权邮件暂未发出，先复制页面上的授权码"));
assert.ok(buyHtml.includes('order.emailDeliveryStatus === "sent"'));
assert.ok(buyHtml.includes("offerdesk.auto.order.id"));
assert.ok(buyHtml.includes("offerdesk.auto.buyer.email"));
assert.ok(buyHtml.includes("offerdesk.auto.buyer.name"));
assert.ok(buyHtml.includes("offerdesk.auto.license.code"));
assert.ok(buyHtml.includes("restoreAutoCheckout()"));
assert.ok(buyHtml.includes("function restoreAutoCheckout"));
assert.ok(buyHtml.includes("function saveAutoOrder"));
assert.ok(buyHtml.includes("function saveAutoLicense"));
assert.ok(buyHtml.includes("function showAutoLicense"));
assert.ok(buyHtml.includes("已恢复订单号"));
assert.ok(buyHtml.includes("已恢复已到账订单，授权码如下。"));
assert.ok(buyHtml.includes("copyTextOrSelect"));
assert.ok(buyHtml.includes('document.execCommand("copy")'));
assert.ok(buyHtml.includes("订单号已选中"));
assert.ok(buyHtml.includes("授权码已选中"));
assert.ok(buyHtml.includes("offerdesk.attribution.source"));
assert.ok(buyHtml.includes('body: JSON.stringify({ email, name: buyerName.value.trim(), source: getAttributionSource() })'));
assert.ok(buyHtml.includes('params.set("source", source)'));
assert.ok(buyHtml.includes("function defaultAttributionSource"));
assert.ok(buyHtml.includes('return "direct-buy"'));
assert.ok(buyHtml.includes('<link rel="stylesheet" href="./site.css" />'));
assert.ok(buyHtml.includes('class="btn primary" id="checkoutButton"'));
assert.ok(buyHtml.includes('checkoutButton.classList.remove("primary")'));
assert.ok(!buyHtml.includes('class="btn green"'));
assert.ok(!buyHtml.includes("border-radius: 999px"));
assert.ok(!buyHtml.includes('font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial'));

assert.ok(afterPayHtml.includes("incomingOrderId"));
assert.ok(afterPayHtml.includes("incomingBuyerEmail"));
assert.ok(afterPayHtml.includes("incomingPayerName"));
assert.ok(afterPayHtml.includes("incomingProject"));
assert.ok(afterPayHtml.includes("incomingQuoteTotal"));
assert.ok(afterPayHtml.includes("setStoredOrderId(incomingOrderId)"));
assert.ok(afterPayHtml.includes("setStoredManualBuyerEmail(incomingBuyerEmail)"));
assert.ok(afterPayHtml.includes("setStoredManualBuyerName(incomingPayerName)"));
assert.ok(afterPayHtml.includes("const resolvedOrderId = incomingOrderId || getStoredOrderId()"));
assert.ok(afterPayHtml.includes('$("payerName").value = incomingPayerName || getStoredManualBuyerName() || resolvedOrderId'));
assert.ok(afterPayHtml.includes("readAttributionSourceFromUrl"));
assert.ok(afterPayHtml.includes("setStoredAttributionSource(incomingSource)"));
assert.ok(afterPayHtml.includes("来源：${getStoredAttributionSource() || \"未记录\"}"));
assert.ok(afterPayHtml.includes("offerdesk.payment.quote.context"));
assert.ok(afterPayHtml.includes("clearStoredQuoteContext()"));
assert.ok(afterPayHtml.includes("报价项目：${quoteContext.project || \"未记录\"}"));
assert.ok(afterPayHtml.includes("报价总价：${formatQuoteTotal(quoteContext) || \"未记录\"}"));
assert.ok(afterPayHtml.includes("function formatQuoteTotal"));
assert.ok(afterPayHtml.includes('function formatLocalDateTime'));
assert.ok(afterPayHtml.includes('$("paidAt").value = formatLocalDateTime(new Date())'));
assert.ok(afterPayHtml.includes("offerdesk.manual.order.id"));
assert.ok(afterPayHtml.includes("offerdesk.manual.buyer.email"));
assert.ok(afterPayHtml.includes("offerdesk.manual.buyer.name"));
assert.ok(afterPayHtml.includes("claim-grid"));
assert.ok(afterPayHtml.includes("orderForSubject"));
assert.ok(afterPayHtml.includes("OfferDesk 专业版授权码领取 ${orderForSubject}"));
assert.ok(afterPayHtml.includes("copyTextOrSelect"));
assert.ok(afterPayHtml.includes('document.execCommand("copy")'));
assert.ok(afterPayHtml.includes("提交内容已选中"));
assert.ok(afterPayHtml.includes("请手动复制：${supportEmail}"));
assert.ok(afterPayHtml.includes('<link rel="stylesheet" href="./site.css" />'));
assert.ok(afterPayHtml.includes('class="btn primary" id="mailLink"'));
assert.ok(!afterPayHtml.includes("border-radius: 999px"));
assert.ok(!afterPayHtml.includes('font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial'));

assert.ok(payHtml.includes("旧付款入口"));
assert.ok(payHtml.includes("去成交页填写邮箱并付款"));
assert.ok(payHtml.includes('<link rel="stylesheet" href="./site.css" />'));
assert.ok(payHtml.includes('class="card old-pay-card"'));
assert.ok(payHtml.includes('class="btn primary" href="./buy.html"'));
assert.ok(!payHtml.includes("https://qr.alipay.com/"));
assert.ok(!payHtml.includes("border-radius: 999px"));
assert.ok(!payHtml.includes('font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial'));

console.log("manual checkout flow tests passed");
