import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const html = await readFile(new URL("../promotion.html", import.meta.url), "utf8");
const pipelineHtml = await readFile(new URL("../pipeline.html", import.meta.url), "utf8");

assert.ok(html.includes("offerdesk-promotion-log-v1"));
assert.ok(html.includes("launch/promotion-log.csv"));
assert.ok(html.includes("date\", \"channel\", \"url\", \"title\", \"status\", \"note"));
assert.ok(html.includes("./site.css"));
assert.ok(html.includes("./pipeline.html"));
assert.ok(html.includes("copyReadinessCommand"));
assert.ok(html.includes("scripts/outreach-readiness.mjs"));
assert.ok(html.includes("launch/outreach-readiness.md"));
assert.ok(html.includes("function selectCopyFallback"));
assert.ok(html.includes('document.execCommand("copy")'));
assert.ok(html.includes("element.select()"));

assert.ok(pipelineHtml.includes("offerdesk-first-sale-pipeline-v1"));
assert.ok(pipelineHtml.includes('<link rel="stylesheet" href="./site.css" />'));
assert.ok(pipelineHtml.includes("<strong>OfferDesk</strong>"));
assert.ok(pipelineHtml.includes('class="btn primary"'));
assert.ok(pipelineHtml.includes("copyReadinessCommand"));
assert.ok(pipelineHtml.includes("scripts/outreach-readiness.mjs"));
assert.ok(pipelineHtml.includes("launch/outreach-readiness.md"));
assert.ok(pipelineHtml.includes("order_id"));
assert.ok(pipelineHtml.includes("source"));
assert.ok(pipelineHtml.includes("--source"));
assert.ok(pipelineHtml.includes("openEmailAfter: true"));
assert.ok(pipelineHtml.includes("defaultManualEmailOut(orderId)"));
assert.ok(pipelineHtml.includes("dist/manual-orders/${safeOrderId}-email.txt"));
assert.ok(pipelineHtml.includes("function selectCopyFallback"));
assert.ok(pipelineHtml.includes('document.execCommand("copy")'));
assert.ok(pipelineHtml.includes("element.select()"));
assert.ok(pipelineHtml.includes("row-actions"));
assert.ok(pipelineHtml.includes("试用私信"));
assert.ok(pipelineHtml.includes("成交私信"));
assert.ok(pipelineHtml.includes("buildTrialMessage"));
assert.ok(pipelineHtml.includes("buildCloseMessage"));
assert.ok(pipelineHtml.includes("buildTrackedUrl"));
assert.ok(pipelineHtml.includes("https://8npyvz5bd8-lang.github.io/offerdesk/"));
assert.ok(pipelineHtml.includes('url.searchParams.set("source", leadSource(lead, fallbackSource))'));
assert.ok(pipelineHtml.includes('["闲鱼", "xianyu"]'));
assert.ok(pipelineHtml.includes('["小红书", "xiaohongshu"]'));
assert.ok(pipelineHtml.includes("29 元专业版去水印"));
assert.ok(pipelineHtml.includes("claimCommand);"));
assert.ok(pipelineHtml.includes("金额 ¥${claim.amount || \"29\"}"));
assert.ok(pipelineHtml.includes("来源 ${claim.source || \"未记录\"}"));
assert.ok(pipelineHtml.includes("先在支付宝核对到账金额和付款备注，再运行发码命令。"));
assert.ok(!pipelineHtml.includes("border-radius: 999px"));
assert.ok(!pipelineHtml.includes('font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial'));

console.log("promotion page tests passed");
